import type { Metadata, Viewport } from "next";
import "./globals.css";
import {
  ClerkProvider,

} from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Watchparty",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/icon2.png" },
      { url: "/icon2.png", sizes: "16x16", type: "image/png" },
      { url: "/icon2.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "/icon2.png", sizes: "180x180" }
    ],
  },
  appleWebApp: {
    title: "Watchparty",
    statusBarStyle: "default",
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  minimumScale: 1,
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}
    >
      <html lang="en">
        <body className="hidden-scrollbar">
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="BRtheme"
          >
            <Toaster theme="light" position="bottom-center"/>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}